# Generated by Django 5.1.1 on 2024-10-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('symbol', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('exchange', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('ADR_percent', models.FloatField()),
                ('SMA_10', models.FloatField()),
                ('SMA_20', models.FloatField()),
                ('SMA_50', models.FloatField()),
                ('SMA_100', models.FloatField()),
                ('SMA_150', models.FloatField()),
                ('SMA_200', models.FloatField()),
                ('ema', models.FloatField()),
                ('rsi', models.FloatField()),
            ],
            options={
                'db_table': 'stock_data',
            },
        ),
    ]
