# Generated by Django 5.0.6 on 2024-11-06 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screener_daily_USA', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stock_data_balance_sheet',
            table='stock_data_balance_sheet_USA',
        ),
        migrations.AlterModelTable(
            name='stock_data_cash_flow',
            table='stock_data_cash_flow_USA',
        ),
        migrations.AlterModelTable(
            name='stock_data_dividends',
            table='stock_data_dividends_USA',
        ),
        migrations.AlterModelTable(
            name='stockdata',
            table='stock_data_indicators_USA',
        ),
    ]
