# Generated by Django 5.0.6 on 2024-11-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener_daily_USA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='ADR_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='SMA_10',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='SMA_100',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='SMA_150',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='SMA_20',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='SMA_200',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='SMA_50',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='ema',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='rsi',
            field=models.FloatField(null=True),
        ),
    ]
