# Generated by Django 5.0.6 on 2024-11-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener_daily_USA', '0002_alter_stock_data_balance_sheet_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_Data_Income_Statement',
            fields=[
                ('symbol', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('exchange', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('logoid', models.CharField(max_length=255, null=True)),
                ('update_mode', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=255, null=True)),
                ('typespecs', models.CharField(max_length=255, null=True)),
                ('total_revenue_ttm', models.FloatField(null=True)),
                ('fundamental_currency_code', models.CharField(max_length=255, null=True)),
                ('total_revenue_yoy_growth_ttm', models.FloatField(null=True)),
                ('gross_profit_ttm', models.FloatField(null=True)),
                ('oper_income_ttm', models.FloatField(null=True)),
                ('net_income_ttm', models.FloatField(null=True)),
                ('ebitda_ttm', models.FloatField(null=True)),
                ('earnings_per_share_diluted_ttm', models.FloatField(null=True)),
                ('earnings_per_share_diluted_yoy_growth_ttm', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'stock_data_income_statement_USA',
            },
        ),
    ]
