# Generated by Django 5.0.6 on 2024-11-05 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screener_daily_USA', '0002_alter_stockdata_adr_percent_alter_stockdata_sma_10_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stockdata',
            table='stock_data_indicators',
        ),
    ]
