# Generated by Django 5.0.6 on 2024-11-05 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screener_daily_USA', '0003_alter_stockdata_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stockdata',
            table='data_indicators',
        ),
    ]
