# Generated by Django 5.0.6 on 2024-11-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener_daily_USA', '0004_stock_data_overview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_Data_Performance',
            fields=[
                ('symbol', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('exchange', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('logoid', models.CharField(max_length=255, null=True)),
                ('update_mode', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=255, null=True)),
                ('typespecs', models.CharField(max_length=255, null=True)),
                ('close', models.FloatField(null=True)),
                ('pricescale', models.FloatField(null=True)),
                ('minmov', models.FloatField(null=True)),
                ('fractional', models.CharField(max_length=255, null=True)),
                ('minmove2', models.FloatField(null=True)),
                ('currency', models.CharField(max_length=255, null=True)),
                ('change', models.FloatField(null=True)),
                ('perf_w', models.FloatField(null=True)),
                ('perf_1m', models.FloatField(null=True)),
                ('perf_3m', models.FloatField(null=True)),
                ('perf_6m', models.FloatField(null=True)),
                ('perf_ytd', models.FloatField(null=True)),
                ('perf_y', models.FloatField(null=True)),
                ('perf_5y', models.FloatField(null=True)),
                ('perf_10y', models.FloatField(null=True)),
                ('perf_all', models.FloatField(null=True)),
                ('volatility_w', models.FloatField(null=True)),
                ('volatility_m', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'stock_data_performance_USA',
            },
        ),
    ]
