# Generated by Django 5.0.6 on 2024-11-05 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screener_daily_USA', '0004_alter_stockdata_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdata',
            name='exchange',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='price',
        ),
    ]
