# Generated by Django 5.0.6 on 2024-11-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener_daily_USA', '0006_stock_data_profitability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_Data_Valuation',
            fields=[
                ('symbol', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('exchange', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255, null=True)),
                ('logoid', models.CharField(max_length=255, null=True)),
                ('update_mode', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=255, null=True)),
                ('typespecs', models.CharField(max_length=255, null=True)),
                ('market_cap_basic', models.FloatField(null=True)),
                ('fundamental_currency_code', models.CharField(max_length=255, null=True)),
                ('perf_1y_market_cap', models.FloatField(null=True)),
                ('price_earnings_ttm', models.FloatField(null=True)),
                ('price_earnings_growth_ttm', models.FloatField(null=True)),
                ('price_sales_current', models.FloatField(null=True)),
                ('price_book_fq', models.FloatField(null=True)),
                ('price_to_cash_f_operating_activities_ttm', models.FloatField(null=True)),
                ('price_free_cash_flow_ttm', models.FloatField(null=True)),
                ('price_to_cash_ratio', models.FloatField(null=True)),
                ('enterprise_value_current', models.FloatField(null=True)),
                ('enterprise_value_to_revenue_ttm', models.FloatField(null=True)),
                ('enterprise_value_to_ebit_ttm', models.FloatField(null=True)),
                ('enterprise_value_ebitda_ttm', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'stock_data_valuation_USA',
            },
        ),
    ]
