# Generated by Django 5.0.6 on 2024-11-06 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screener_daily_USA', '0008_ndx_components_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ndx_components',
            table='stock_NDX_components_USA',
        ),
    ]
