# Generated by Django 5.0.6 on 2024-11-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener_daily_USA', '0009_alter_ndx_components_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPX_Components',
            fields=[
                ('symbol', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('spx_components', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('logoid', models.CharField(max_length=255, null=True)),
                ('update_mode', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=255, null=True)),
                ('typespecs', models.CharField(max_length=255, null=True)),
                ('market_cap_basic', models.FloatField(null=True)),
                ('fundamental_currency_code', models.CharField(max_length=255, null=True)),
                ('close', models.FloatField(null=True)),
                ('pricescale', models.FloatField(null=True)),
                ('minmov', models.FloatField(null=True)),
                ('fractional', models.CharField(max_length=255, null=True)),
                ('minmove2', models.FloatField(null=True)),
                ('currency', models.CharField(max_length=255, null=True)),
                ('change', models.FloatField(null=True)),
                ('volume', models.FloatField(null=True)),
                ('relative_volume_10d_calc', models.FloatField(null=True)),
                ('price_earnings_ttm', models.FloatField(null=True)),
                ('earnings_per_share_diluted_ttm', models.FloatField(null=True)),
                ('earnings_per_share_diluted_yoy_growth_ttm', models.FloatField(null=True)),
                ('dividends_yield_current', models.FloatField(null=True)),
                ('sector_tr', models.CharField(max_length=255, null=True)),
                ('market', models.CharField(max_length=255, null=True)),
                ('sector', models.CharField(max_length=255, null=True)),
                ('recommendation_mark', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'stock_SPX_components_USA',
            },
        ),
    ]
