# Generated by Django 5.0.6 on 2024-12-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPAccess',
            fields=[
                ('ip_address', models.CharField(default='0.0.0.0', max_length=255, primary_key=True, serialize=False)),
                ('expiration_date', models.DateField()),
            ],
            options={
                'db_table': 'ip_access',
            },
        ),
    ]
