# Generated by Django 5.0.6 on 2024-11-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_telegram_bot', '0002_ipaccess_delete_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaccess',
            name='user_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ipaccess',
            name='expiration_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ipaccess',
            name='ip_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
