# Generated by Django 5.0.6 on 2024-11-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener_daily_USA', '0002_stock_merge_all_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_data_indicators',
            name='quick_filter_1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock_data_indicators',
            name='quick_filter_2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock_data_indicators',
            name='quick_filter_3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock_data_indicators',
            name='quick_filter_4',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock_data_indicators',
            name='quick_filter_5',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock_data_indicators',
            name='quick_filter_6',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock_merge_all_tables',
            name='quick_filter_1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock_merge_all_tables',
            name='quick_filter_2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock_merge_all_tables',
            name='quick_filter_3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock_merge_all_tables',
            name='quick_filter_4',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock_merge_all_tables',
            name='quick_filter_5',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock_merge_all_tables',
            name='quick_filter_6',
            field=models.FloatField(null=True),
        ),
    ]
