# Generated by Django 5.0.6 on 2024-11-21 11:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=200)),
                ('expiration_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'ip_access',
            },
        ),
        migrations.DeleteModel(
            name='Access',
        ),
    ]
