# Generated by Django 5.0.6 on 2024-11-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_telegram_bot', '0003_ipaccess_user_id_alter_ipaccess_expiration_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipaccess',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='ipaccess',
            name='ip_address',
            field=models.CharField(default='0.0.0.0', max_length=255, unique=True),
        ),
    ]
